# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'DaCops Spielwiese(bf9d6030-5581-4277-b05c-d38380e4ee32)'
    subscriptionId: 'bf9d6030-5581-4277-b05c-d38380e4ee32'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mjlab-mgmt'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '/docs/reference/mjlab/armTemplates/template.json'
    csmParametersFile: '/docs/reference/mjlab/armTemplates/parameter.json'
    deploymentMode: 'Incremental'